
import { GoogleGenAI } from "@google/genai";

export const generatePixelImage = async (userPrompt: string): Promise<string> => {
  // Wrap prompt as requested
  const systemPrompt = `sharp 64x64 pixel art on a solid background, flat colors, retro game aesthetic, no gradients or blurs. Subject: ${userPrompt}`;
  
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: systemPrompt,
      config: {
        numberOfImages: 1,
        aspectRatio: '1:1',
        outputMimeType: 'image/png'
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64Data = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64Data}`;
    }
    
    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
